steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install", "--legacy-peer-deps"]
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
    env:
      - "NEXT_PUBLIC_LIVE_SERVER=${_NEXT_PUBLIC_LIVE_SERVER}"
      - "NEXT_PUBLIC_TEST_SERVER=${_NEXT_PUBLIC_TEST_SERVER}"
      - "NEXT_PUBLIC_MEDIA_BUCKET=${_NEXT_PUBLIC_MEDIA_BUCKET}"
      - "NEXT_PUBLIC_GAME_BUCKET=${_NEXT_PUBLIC_GAME_BUCKET}"
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/upsurge-cloud/frontend:latest", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/upsurge-cloud/frontend:latest"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "frontend",
        "--platform",
        "managed",
        "--region",
        "us-central1",
        "--image",
        "gcr.io/upsurge-cloud/frontend:latest",
        "--allow-unauthenticated",
        "--update-env-vars",
        "NEXT_PUBLIC_LIVE_SERVER=${_NEXT_PUBLIC_LIVE_SERVER},NEXT_PUBLIC_TEST_SERVER=${_NEXT_PUBLIC_TEST_SERVER},NEXT_PUBLIC_MEDIA_BUCKET=${_NEXT_PUBLIC_MEDIA_BUCKET},NEXT_PUBLIC_GAME_BUCKET=${_NEXT_PUBLIC_GAME_BUCKET}",
      ]
images:
  - "gcr.io/upsurge-cloud/frontend:latest"
options:
  logging: CLOUD_LOGGING_ONLY
