steps:
  # Step 1: Install dependencies
  - name: "gcr.io/cloud-builders/npm"
    args: ["install", "--legacy-peer-deps"]

  # Step 2: Build the Next.js application
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
    env:
      - "NEXT_PUBLIC_LIVE_SERVER=${_NEXT_PUBLIC_LIVE_SERVER}"
      - "NEXT_PUBLIC_TEST_SERVER=${_NEXT_PUBLIC_TEST_SERVER}"
      - "NEXT_PUBLIC_MEDIA_BUCKET=${_NEXT_PUBLIC_MEDIA_BUCKET}"
      - "NEXT_PUBLIC_GAME_BUCKET=${_NEXT_PUBLIC_GAME_BUCKET}"

  # Step 3: Deploy the image to Google Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "frontend",
        "--platform",
        "managed",
        "--region",
        "us-central1",
        "--image",
        "us-central1-docker.pkg.dev/upsurge-cloud/cloud-run-source-deploy/frontend/frontend:72e2e77e425d88bd9aa465fedfbf472d3ab186f4",
        "--allow-unauthenticated",
        "--update-env-vars",
        "NEXT_PUBLIC_LIVE_SERVER=${_NEXT_PUBLIC_LIVE_SERVER},NEXT_PUBLIC_TEST_SERVER=${_NEXT_PUBLIC_TEST_SERVER},NEXT_PUBLIC_MEDIA_BUCKET=${_NEXT_PUBLIC_MEDIA_BUCKET},NEXT_PUBLIC_GAME_BUCKET=${_NEXT_PUBLIC_GAME_BUCKET}",
      ]

images:
  - "us-central1-docker.pkg.dev/upsurge-cloud/cloud-run-source-deploy/frontend/frontend:72e2e77e425d88bd9aa465fedfbf472d3ab186f4"

options:
  logging: CLOUD_LOGGING_ONLY
