export const Game_Data = {
  DontOverspend: {
    name: "Shopping budget",
    description: "Can stay within your budget at the mall?",
    //img: "https://upsurgevideoassets.s3.ap-south-1.amazonaws.com/images/SB.png",
    img: "/images/games/dont-overspend.png",
    pushto: "/games/DontOverspend",
    changedId: "DontOverspend",
    premium_plan: 0,
    webgl_key: "ShoppingBudget_WebGL",
  },
  BalanceBuilder: {
    name: "Balance builder",
    //img: "https://upsurgevideoassets.s3.ap-south-1.amazonaws.com/images/BalanceBuilder.png",
    img: "/images/games/balance-builder.png",
    description: "How does your bank balance change with different events?",
    premium_plan: 0,
    webgl_key: "BalanceBuilder_WebGL",
  },
  HighAndLow: {
    name: "High and low",
    changedId: "HighAndLow",
    description:
    "Check how much money each column has, and arrange it in ascending or descending order.",
    img: "/images/games/high-and-low.png",
    //img: "https://upsurgevideoassets.s3.ap-south-1.amazonaws.com/images/HighandLow.png",
    premium_plan: 0,
    webgl_key: "HignAndLow_WebGL",
  },
  MoneyMath: {
    name: "Money maths",
    description:
    "Let’s earn some money to buy what you want! Make sure you have enough before checking out.",
    //img: "https://upsurge.in/images/games/MoneyMath.png",
    img: "/images/games/money-math.png",
    premium_plan: 0,
    webgl_key: "MoneyMaths_WebGL",
  },
  MoneyManager: {
    name: "Money manager",
    //img: "https://upsurgevideoassets.s3.ap-south-1.amazonaws.com/images/MoneyManager.png",
    img: "/images/games/money-manager.png",
    description: "Earn money, & divide it between Saving, Expenses & Charity.",
    premium_plan: 0,
    webgl_key: "MoneyManager_WebGL",
  },
  MoneySlide: {
    name: "Money slide",
    //img: "https://upsurgevideoassets.s3.ap-south-1.amazonaws.com/images/MoneySlide.png",
    img: "/images/games/money-slide.png",
    description: "Fill each piggy-bank with the right amount of money.",
    premium_plan: 0,
    webgl_key: "MoneySlide_WebGL",
  },
  NeedOrWant: {
    name: "Need and want",
    description:
    "What is the difference between a need & a want? Let’s play to find out.",
    img: "/images/games/need-and-want.png",
    //img: "https://upsurgevideoassets.s3.ap-south-1.amazonaws.com/images/NeedorWant.png",
    premium_plan: 0,
    webgl_key: "NeedsAndWants_WebGL",
  },
  Ludo: {
    name: "Ludo",
    description:
      "Our adaptation of the age-old classic! Answer financial questions & get bonus moves. Let’s see how fast you can finish this 2-pawn version.",
    img: "/images/games/ludo-game.png",
    premium_plan: 0,
    webgl_key: "Ludo_WebGL",
  },
  MoneyDash: {
    name: "Money Dash",
    description: "Learn to manage expenses on the fly.",
    img: "/images/games/money-dash.png",
    //img: "https://upsurgevideoassets.s3.ap-south-1.amazonaws.com/images/MoneyDash.png",
    premium_plan: 0,
    webgl_key: "MoneyDash_WebGL",
  },
  SnakeAndLadders: {
    name: "Snake And Ladders",
    description:
    "Learn about money management with our 3D adaptation of this classic.",
    img: "/images/games/snake-and-ladders.png",
    //img: "https://upsurgevideoassets.s3.ap-south-1.amazonaws.com/images/Snake%26Ladders.png",
    premium_plan: 1001,
    webgl_key: "SnakesAndLadder_WebGL",
  },
  PriceIsRight: {
    name: "Price Is Right",
    description:
    "Learn about money management with our budget simulator.",
    img: "/images/games/price-is-right.png",
    //img: "https://upsurgevideoassets.s3.ap-south-1.amazonaws.com/images/Snake%26Ladders.png",
    premium_plan: 1001,
    webgl_key: "PriceIsRight_WebGL",
  },
  WorldBank: {
    name: "World Bank",
    description:
    "Get behind a bank counter and learn about banking and credit economy.",
    img: "/images/games/world-bank.png",
    //img: "https://upsurgevideoassets.s3.ap-south-1.amazonaws.com/images/Snake%26Ladders.png",
    premium_plan: 1001,
    webgl_key: "WorldBank_WebGL",
  },
  MiniMiner: {
    name: "Mini Miner",
    description:
    "Get behind a mine and earn as much as you can.",
    img: "/images/games/mini-miner.png",
    //img: "https://upsurgevideoassets.s3.ap-south-1.amazonaws.com/images/Snake%26Ladders.png",
    premium_plan: 1001,
    webgl_key: "MiniMiner_WebGL",
  },
};

export const Simulator_Data = {
  Stock: {
    name: "Stock Simulator",
    description: "Go in a virtual simulator to learn about stock trading.",
    img: "https://imgcdn.upsurge.in/images/Pngtree-cartoon-hand-drawn-dollar-trading-3692475.png",
    pushto: "/dashboard/k/stocksimulator/home",
  },
  Crypto: {
    name: "Crypto Simulator",
    description: "Go in a virtual simulator to learn about crypto trading.",
    img: "https://imgcdn.upsurge.in/images/free-bitcoin-icon-2207-thumb.png",
    pushto: "/dashboard/k/cryptosimulator/home",
  },
};

export const Download_Games_Data = {
  MoneyAce: {
    name: "Money Ace",
    description: "Go in a virtual simulator to learn about stock trading.",
    logo: "/images/DownloadGames/money_ace_logo.png",
    images: [
      "/images/DownloadGames/money_ace/Money_ace_1.png",
      "/images/DownloadGames/money_ace/Money_ace_2.png",
      "/images/DownloadGames/money_ace/Money_ace_3.png",
    ],
    android_link: "/download/moneyace.apk",
    windows_link: "",
    playstore: "",
    microsoft: "",
  },
  WorldBank: {
    name: "World Bank",
    description: "Go in a virtual simulator to learn about stock trading.",
    logo: "/images/DownloadGames/world_bank.png",
    images: [
      "/images/DownloadGames/world_bank/image.png",
      "/images/DownloadGames/world_bank/image_1.png",
      "/images/DownloadGames/world_bank/image_2.png",
      "/images/DownloadGames/world_bank/image_3.png",
      "/images/DownloadGames/world_bank/image_4.png",
      "/images/DownloadGames/world_bank/image_6.png",
      "/images/DownloadGames/world_bank/image_7.png",
    ],
    android_link: "/download/moneyace.apk",
    windows_link: "",
    playstore: "",
    microsoft: "",
  },
  SNL: {
    name: "S&L",
    description: "Go in a virtual simulator to learn about stock trading.",
    logo: "/images/DownloadGames/snl.png",
    images: [
      "/images/DownloadGames/snl/Image_1.png",
      "/images/DownloadGames/snl/Image_2.png",
      "/images/DownloadGames/snl/Image_3.png",
      "/images/DownloadGames/snl/Image_4.png",
    ],
    android_link: "/download/moneyace.apk",
    windows_link: "",
    playstore: "",
    microsoft: "",
  },
  SuperApp: {
    name: "Super App",
    description: "Go in a virtual simulator to learn about stock trading.",
    logo: "/images/DownloadGames/games_hub.png",
    images: [
      "/images/DownloadGames/superapp/Image_1.png",
      "/images/DownloadGames/superapp/Image_2.png",
      "/images/DownloadGames/superapp/Image_3.png",
      "/images/DownloadGames/superapp/Image_4.png",
      "/images/DownloadGames/superapp/Image_5.png",
      "/images/DownloadGames/superapp/Image_6.png",
      "/images/DownloadGames/superapp/Image_7.png",
    ],
    android_link: "/download/moneyace.apk",
    windows_link: "",
    playstore: "",
    microsoft: "",
  },
  GourmetEmpire: {
    name: "Gourmet Empire",
    description: "Go in a virtual simulator to learn about stock trading.",
    logo: "/images/DownloadGames/gourmet_empire.png",
    images: [
      "/images/DownloadGames/gourmet_empire/Image_1.png",
      "/images/DownloadGames/gourmet_empire/Image_2.png",
      "/images/DownloadGames/gourmet_empire/Image_3.png",
      "/images/DownloadGames/gourmet_empire/Image_4.png",
      "/images/DownloadGames/gourmet_empire/Image_5.png",
      "/images/DownloadGames/gourmet_empire/Image_6.png",
    ],
    android_link: "/download/moneyace.apk",
    windows_link: "",
    playstore: "",
    microsoft: "",
  },
};
