name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: "latest"
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Debug - Print Service Account Key
        run: |
          echo "Service Account Key is set"

      - name: Configure Docker for GCR
        run: |
          echo ${{ secrets.GCP_SA_KEY }} > /tmp/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcloud-service-key.json
          gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/frontend .
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/frontend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy frontend --image gcr.io/${{ secrets.GCP_PROJECT }}/frontend --platform managed --region us-central1 --set-env-vars NEXT_PUBLIC_MEDIA_BUCKET=https://storage.googleapis.com,NEXT_PUBLIC_GAME_BUCKET=https://storage.googleapis.com,NEXT_PUBLIC_LIVE_SERVER=https://server-g5bprkvzla-uc.a.run.app/,NEXT_PUBLIC_TEST_SERVER=https://server-g5bprkvzla-uc.a.run.app/
