# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - upsurge - test version

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - ".husky"
      - ".github/**"
      - "**/*.csv"
      - .env*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: npm install, build, and test
        run: |
          npm install --legacy-peer-deps
          echo "${{ secrets.FRONTEND_PROD_CONFIG }}" | base64 -d > config.js | echo "${{ secrets.FRONTEND_PROD_FIREBASE }}" | base64 -d > src/firebase.js | cat config.js | cat src/firebase.js |
          npm run devbuild --if-present

      - name: Zip all files for upload between jobs
        # IMPORTANT: .next is a hidden folder and will NOT be included in the zip unless we specify it
        # To fix: /home/site/wwwroot/node_modules/.bin/next: 1: ../next/dist/bin/next: not found
        run: zip next.zip ./* .next .env -qr

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'upsurge'
          slot-name: 'test'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_93C27B1FE22D47ADBA4E27DCE792E291 }}
          package: next.zip
  
   
